kind: ConfigMap
apiVersion: v1
metadata:
 name: backend
 namespace: expense
data:
 DB_HOST: mysql
--- 
kind: Deployment
apiVersion: apps/v1
metadata:
  name: backend
  namespace: expense
  labels:
    poject: expense
    app: backend
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      project: expense
      app: backend
      tier: backend
  template:
    metadata:
      labels:
        project: expense
        app: backend
        tier: backend
    spec: 
      containers:
      - name: nginx
        image: kittukrish/backend:1.0.0
        envFrom:
        - configMapRef:
             name: backend
---
kind: Service
apiVersion: v1
metadata:
  name: backend
  namespace: expense
spec:
  selector:
     project: expense
     app: backend
     tier: backend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080




      
