kind: Deployment
apiVersion: apps/v1
metadata:
  name: frontend
  namespace: expense
  labels:
    poject: expense
    app: frontend
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      project: expense
      app: frontend
      tier: frontend
  template:
    metadata:
      labels:
        project: expense
        app: frontend
        tier: frontend
    spec: 
      containers:
      - name: nginx
        image: kittukrish/frontend:1.0.0
---
kind: Service
apiVersion: v1
metadata:
  name: frontend
  namespace: expense
spec:
  type: LoadBalancer
  selector:
     project: expense
     app: frontend
     tier: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80




      
